name: BackstopJS Visual Regression Tests

on:
  push:
    branches: [main, develop]
  pull_request_target:
    types: [opened, closed, synchronize, reopened]
    branches: [main, develop]
  workflow_dispatch:

jobs:
  visual-regression:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      pull-requests: write

    outputs:
      has-diffs: ${{ steps.detect-diffs.outputs.diffs }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event_name == 'workflow_dispatch' && github.repository || github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event_name == 'workflow_dispatch' && github.ref || github.event.pull_request.head.ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm playwright install --with-deps chromium

      - name: Build Storybook
        run: pnpm build-storybook

      - name: Serve Storybook
        run: |
          npx http-server ./storybook-static -p 6006 > /dev/null 2>&1 &
          npx wait-on http://localhost:6006/iframe.html

      - name: Run BackstopJS tests
        id: detect-diffs
        run: |
          pnpm backstop:test && echo "diffs=false" >> $GITHUB_OUTPUT || echo "diffs=true" >> $GITHUB_OUTPUT

      - name: Upload BackstopJS complete report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backstop-complete-report
          path: backstop_data/
          retention-days: 30

      - name: Upload report artifact for deployment
        if: steps.detect-diffs.outputs.diffs == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: gh-pages-artifact
          path: backstop_data/html_report/
          retention-days: 1

      - name: Comment PR with report link
        if: steps.detect-diffs.outputs.diffs == 'true' && github.event_name == 'pull_request_target'
        uses: actions/github-script@v7
        with:
          script: |
            const branchSafe = (context.payload.pull_request.head.ref || context.ref).replace(/\//g, "-");
            const pagesUrl = `https://${context.repo.owner}.github.io/${context.repo.repo}/reports/${branchSafe}/`;
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;
            const comment = `
            ## 📸 Visual Regression Test Results
            ⚠️ Visual differences detected

            ### 📊 Test Artifacts
            - 🔗 **[BackstopJS Complete Report](${pagesUrl})** – View live report
            - 🧾 **[Workflow Artifacts](${runUrl}#artifacts)**

            ### 📋 Report Includes:
            - Side-by-side screenshots (reference vs. test)
            - Highlighted visual diffs
            - Interactive viewer

            🕒 Artifacts are retained for 30 days.`;

            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });

      - name: Notify if Storybook failed
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "❌ Visual regression tests failed. Storybook or test runner may not have started correctly. Please check the workflow logs."
            });

  deploy-pages:
    needs: visual-regression
    if: needs.visual-regression.outputs.has-diffs == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout gh-pages branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git clone --depth=1 --branch=gh-pages https://github.com/${{ github.repository }} gh-pages
          cp -r gh-pages-artifact/reports/* gh-pages/reports/
          cd gh-pages
          git add .
          git commit -m "chore: deploy BackstopJS report for ${{ github.ref_name }}"
          git push

  approve-backstop:
    if: github.event_name == 'pull_request_target' && github.event.action == 'closed' && github.event.pull_request.merged == true && (github.event.pull_request.base.ref == 'main' || github.event.pull_request.base.ref == 'develop')
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
          cache-dependency-path: "front/yarn.lock"

      - name: Install dependencies
        run: |
          cd front
          yarn install --frozen-lockfile

      - name: Approve BackstopJS references
        run: |
          cd front
          yarn backstop:approve

      - name: Commit and push approved references
        run: |
          cd front
          git config user.name "anticor"
          git config user.email "anticor@users.noreply.github.com"
          git add backstop_data/bitmaps_reference
          git commit -m "chore: approve BackstopJS references post-merge [skip ci]" || echo "No changes to commit"
          git push
